blog_project_app/urls.py
# -*- coding:utf-8 -*-
"""blog_project_app URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.views.static import  serve #处理静态文件
from django.conf.urls import url,include
# from django.contrib import admin
import xadmin
from blog_project_app import settings
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'xadmin/', xadmin.site.urls),
    url(r'',include('blog.urls')),
    url(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),#处理上传文件路径,
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),

]
#全局404 500
handler404 = 'blog.views.page_not_fount'
handler500 = 'blog.views.page_error'


from django.conf import settings

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
# -*- coding:utf-8 -*-
from __future__ import unicode_literals

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.core.urlresolvers import reverse



@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='分类名称')
    is_tab = models.BooleanField(default=False,verbose_name='是否放在导航')
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '分类'


@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name='标签名称')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '标签'


@python_2_unicode_compatible
class Article(models.Model):
    title = models.CharField(max_length=100, verbose_name='文章标题')
    # body = UEditorField('内容', height=600, width=900,
    #     default=u'', blank=True, imagePath="uploads/images/",
    #     toolbars='besttome', filePath='uploads/files/')
    body = models.TextField(verbose_name='文章正文')
    recom = models.BooleanField(verbose_name='是否推荐',default=False)
    excerpt = models.CharField(max_length=255, blank=True, verbose_name='文章摘要')
    create_time = models.DateTimeField(auto_now_add=True, editable=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')
    category = models.ForeignKey(Category, verbose_name='分类')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')
    author = models.ForeignKey(User, verbose_name='作者')
    is_related = models.BooleanField(default=False,verbose_name='是否推荐')
    view = models.PositiveIntegerField(default=0, verbose_name='访问量')
    image = models.ImageField(upload_to='article/%Y/%m',verbose_name='封面图',default='default/default.png',blank=True,null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'id': self.pk})

    class Meta:
        ordering = ['-create_time']
        verbose_name_plural = verbose_name = '文章'


@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100, verbose_name='名字')
    email = models.EmailField(max_length=255, verbose_name='邮箱')
    text = models.TextField(verbose_name='评论内容')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    article = models.ForeignKey(Article, verbose_name='所属文章')

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = verbose_name = '评论'
        ordering = ['-create_time']


@python_2_unicode_compatible
class Banner(models.Model):
    title = models.CharField(max_length=100, verbose_name='标题')
    index = models.IntegerField(default=0,verbose_name='优先')
    active = models.CharField(max_length=10,verbose_name='是否为选中状态',null=True,blank=True)
    images = models.ImageField(upload_to='banner/%Y/%m', verbose_name='图片')
    upload_time = models.DateTimeField(auto_now_add=True, verbose_name='上传时间')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = verbose_name = '轮播图'
@python_2_unicode_compatible
class Links(models.Model):
    name = models.CharField(max_length=100,verbose_name='网站名称')
    url = models.URLField(verbose_name='链接')
    create_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural=verbose_name='友情链接'

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/archives.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags %}
{% block coutom_css %}
<style>
  .year{
      margin-bottom: 1rem;
      font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
      font-size: 18px;
  }
  .year li{
      padding-left: 3rem!important;
  }
</style>
{% endblock %}
{% block title %}
    <title>归档</title>
{% endblock %}
{% block content %}
    <div class="content">
        {#{% archives as date_list %}#}
        {#{% for date in date_list %}#}
        {#<li>#}
        {#  <a href="">#}
        {#    {{ date.year }} 年 {{ date.month }} 月#}
        {#  </a>#}
        {#</li>#}
        {#{% endfor %}#}
        <div class="widget widget-archives">
            <h3 class="widget-title">归档</h3>
            {% archives as archiveslist %}
            {% regroup archiveslist by create_time.year as year_post_group %}
            <ul class="year">
                {% for year in year_post_group %}
                <li >{{ year.grouper }} 年
                    {% regroup year.list by create_time.month as month_post_group %}
                    <ul class="month">
                        {% for month in month_post_group %}
                        <li>{{ month.grouper }}
                            月({{ month.list | length }})
                            <ul class="archives-post">
                                {% for post in month.list %}
                                <li><a href="{% url 'post' post.id %}">{{ post.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>



                        {% endfor %}
                    </ul>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

templates/base.html
<!doctype html>
{% load staticfiles %}
{% load blog_tags %}
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}<title>Home</title>{% endblock %}
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nprogress.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">

    <link rel="apple-touch-icon-precomposed" href="{% static 'images/favicon.ico' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'js/nprogress.js' %}"></script>
    <script src="{% static 'js/jquery.lazyload.min.js' %}"></script>

    {% block coutom_js %}

    {% endblock %}
    {% block coutom_css %}
    {% endblock %}
<!--     [if gte IE 9]> -->
  <script src="{% static 'js/jquery-1.11.1.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/html5shiv.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/respond.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/selectivizr-min.js' %}" type="text/javascript"></script>
<!-- <![endif]
   {# <!--[if lt IE 9]> #}
  <script>window.location.href='upgrade-browser.html';</script>
<!endif --> 
</head>
<body class="user-select">
<header class="header">
    <nav class="navbar navbar-default" id="navbar">
        <div class="container">
            <div class="header-topbar hidden-xs link-border">
                <ul class="site-nav topmenu">
                {% if request.user.is_authenticated %}
                    <li><i class="fa fa-user" aria-hidden="true"></i> {{ request.user.username }}</li>
                              <li><a href="{% url 'user_logout' %}" rel="nofollow"> <i class="fa fa-sign-out" aria-hidden="true"></i> 退出</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}" rel="nofollow"><i class="fa fa-sign-in" aria-hidden="true"></i> 登录</a></li>
                    <li><a href="{% url 'register' %}" title="注册"><i class="fa fa-registered" aria-hidden="true"></i>
                        注册
                    </a>
                {% endif %}
                    </li>
                </ul>
                勤记录 懂分享
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#header-navbar" aria-expanded="false"><span class="sr-only"></span> <span
                        class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>
                <h1 class="logo hvr-bounce-in"><a href="{% url 'index' %}" title="方少会的个人博客"><img src="{% static 'images/logo.png' %}"
                                                                               alt="方少会的个人博客"></a></h1>
            </div>
            <div class="collapse navbar-collapse" id="header-navbar">
                <form class="navbar-form visible-xs" action="{% url 'search' %}" method="get">
                    <div class="input-group">
                        <input type="text" name="keyword" class="form-control" placeholder="请输入关键字" maxlength="20"
                               autocomplete="off">
                        <span class="input-group-btn">
		<button class="btn btn-default btn-search"  type="submit">搜索</button>
		</span></div>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a data-cont="方少会的个人博客" title="方少会的个人博客" href="{% url 'index' %}"><i class="fa fa-home mr-1"></i> 首页</a></li>
                    <li><a data-cont="归档" title="归档" href="{% url 'archives_all' %}"> <i class="fa fa-bar-chart" aria-hidden="true"></i> 归档</a></li>
                    <li><a data-cont="关于" title="关于" href="#"><i class="fa fa-recycle" aria-hidden="true"></i> 关于</a></li>
                    <li><a data-cont="RSS订阅" title="RSS订阅" href="{% url 'rss' %}"><i class="fa fa-rss-square" aria-hidden="true"></i> RSS订阅</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>
    <section class="container">
        <div class="content-wrap">
            {% block content %}
            {% endblock %}
        </div>
            {% block sidebar %}
              <aside class="sidebar">
                            <div class="widget widget_search">
                <form class="navbar-form" action="{% url 'search' %}" method="get">
                    <div class="input-group">
                        <input type="text" name="keyword" class="form-control" size="35" placeholder="请输入关键字"
                               maxlength="15" autocomplete="off">
                        <span class="input-group-btn">
		<button class="btn btn-default btn-search"  type="submit">搜索</button>
		</span></div>
                </form>
            </div>
  <div class="widget widget_sentence">
  <h3><i class="fa fa-tags"> 标签云</i></h3>
  <div class="widget-sentence-content">
    <ul class="plinks ptags">
            {% get_tags as tag_list %}
            {% for tag in tag_list %}
            <li><a href="{% url 'tag' tag.id %}" title="{{ tag.name }}" draggable="false">{{ tag.name }} <span class="badge">{{ tag.article_set.count }}</span></a></li>
            {% endfor %}

    </ul>
  </div>
  </div>
      <div class="widget widget_sentence">
  <h3><i class="fa fa-book mr-2 f-17"> 分类</i></h3>
  <div class="widget-sentence-content">
    <ul class="plinks ptags">
            {% get_categories as cate_list %}
            {% for cate in cate_list %}
            <li><a href="{% url 'category' cate.id %}" title="{{ cate.name }}" draggable="false">{{ cate.name }} <span class="badge">{{ cate.article_set.count }}</span></a></li>
            {% endfor %}

    </ul>
  </div>
  </div>
        <div class="widget widget_hot">
            <h3><i class="fa fa-comments"> 最新评论文章</i></h3>
            <ul>
                {% for comment in comments %}
                <li><a title="{{ comment_article.title }}" href="{% url 'post' comment.id %}"><span class="thumbnail">
				<img class="thumb" data-original="{{ MEDIA_URL }}{{ comment.image }}" src="{{ MEDIA_URL }}{{ comment.image }}"
                     alt="{{ comment.title }}" style="display: block;">
			</span><span class="text">{{ comment.title }}</span><span class="muted"><i
                        class="glyphicon glyphicon-time"></i>
				{{ comment.create_time|date:"Y-m-d H:m:i"|strtime }}
			</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>{{ comment.view }}</span></a></li>
            {% endfor %}
            </ul>
        </div>
        <div class="widget widget_sentence">
            <h3><i class="fa fa-exchange" aria-hidden="true"></i> 友情链接</h3>

            <div class="widget-sentence-link">
                 {% for link in links %}
                <a href="{{ link.url }}" title="{{ link.name }}" target="_blank">{{ link.name }}</a>&nbsp;&nbsp;&nbsp;
            {% endfor %}
            </div>



        </div>
    </aside>
            {% endblock %}

    </section>
<footer class="footer">
    <div class="container">
        <p>Copyright &copy; 2018.Company name All rights reserved.<a target="_blank" href="http://sc.chinaz.com/moban/">muban</a> Django1.11.8

        </p>

    </div>
    <div id="gotop"><a class="gotop"></a></div>
</footer>
</body>
{% block js %}{% endblock %}
{% block css %}{% endblock %}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.ias.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script type="text/javascript">
    $("img.thumb").lazyload({
    placeholder: "{% static 'images/occupying.png' %}",
    effect: "fadeIn"
});
$(".single .content img").lazyload({
    placeholder: "{% static '/images/occupying.png' %}",
    effect: "fadeIn"
});
$('[data-toggle="tooltip"]').tooltip();
jQuery.ias({
    history: false,
    container: '.content',
    item: '.excerpt',
    pagination: '.pagination',
    next: '.next-page a',
    trigger: '查看更多',
    loader: '<div class="pagination-loading"><img src="{% static 'images/loading.gif' %}" /></div>',
    triggerPageThreshold: 5,
    onRenderComplete: function() {
        $('.excerpt .thumb').lazyload({
            placeholder: '../images/occupying.png',
            threshold: 400
        });
        $('.excerpt img').attr('draggable', 'false');
        $('.excerpt a').attr('draggable', 'false')
    }
});
</script>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}
    <title>方少会的个人博客</title>
{% endblock %}
{% load staticfiles %}
{% load blog_tags %}
{#{% block coutom_js %}#}
{#     <script type="text/javascript">#}
{#        var nowTime ;#}
{#        function play(){#}
{#        var time = new Date();#}
{#        nowTime = time.getFullYear()+"年"+time.getMonth()+"月"+time.getDate()+"日"+time.getHours()+"时"+time.getMinutes()+"分"+time.getSeconds()+"秒";#}
{#        document.getElementById("d").innerHTML = nowTime;#}
{#        }#}
{#        setInterval(play,1000);#}
{#    </script>#}
{#    {% endblock %}#}
{% block content %}
    <div class="content">
        <div id="focusslide" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                {% for nums in all_banner %}
                    <li data-target="#focusslide" data-slide-to="{{ nums.index }}"
                        class="{{ nums.active }}"></li>
                {% endfor %}
            </ol>
            <div class="carousel-inner" role="listbox">
                {% for ban in all_banner %}
                    <div class="item {{ ban.active }}">
                        <a href="#" target="_blank" title="{{ ban.title }}">
                            <img src="{{ MEDIA_URL }}{{ ban.images }}" alt="{{ ban.title }}"
                                 class="img-responsive"></a>
                    </div>
                {% endfor %}
            </div>
            <a class="left carousel-control" href="#focusslide" role="button" data-slide="prev" rel="nofollow">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span
                    class="sr-only">上一个</span>
            </a> <a class="right carousel-control" href="#focusslide" role="button" data-slide="next"
                    rel="nofollow"> <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">下一个</span> </a></div>

            {% for related in related_article %}
        <article class="excerpt-minic excerpt-minic-index">
            <h2><span class="red">【推荐】</span><a target="_blank" href="{% url 'post' related.id %}" title="{{ related.title }}">{{ related.title }}</a>
            </h2>
            <p class="note">{{ related.excerpt }}</p>
        </article>
        {% endfor %}


        <div class="title">
            <h3>最新发布</h3>
            <div class="more">

               {% for tab_category in is_tab %}
               <a href="{% url 'category' tab_category.id %}" title="{{ tab_category.name }}">{{ tab_category.name }}</a>
               {% endfor %}


            </div>
        </div>

        {% for article in all_article.object_list %}
            <article class="excerpt excerpt-{{ article.id }}" style="">
                <a class="focus" href="#" title="{{ article.title }}" target="_blank"><img class="thumb"
                                                                                           data-original="{{ MEDIA_URL }}{{ article.image }}"
                                                                                           src="{{ MEDIA_URL }}{{ article.image }}"
                                                                                           alt="{{ article.title }}"
                                                                                           style="display: inline;"></a>
                <header><a class="cat" href="#" title="MZ-{{ article.category }}">{{ article.category }}<i></i></a>
                    <h2><a href="{% url 'post' article.id %}" title="{{ article.title }}"
                           target="_blank">{{ article.title }}</a>
                    </h2>
                </header>
                <p class="meta">
                    <time class="time"><i class="glyphicon glyphicon-time"></i> {{ article.create_time|date:"Y-m-d H:m:i"|strtime }}</time>
                    <span class="views"><i class="glyphicon glyphicon-eye-open"></i> {{ article.view }}</span>
                    <a class="comment"
                       href="##comment"
                       title="评论"
                       target="_blank"><i
                            class="glyphicon glyphicon-comment"></i> {{ article.comment_set.count}}</a>
                </p>
                <p class="note">{{ article.excerpt }}</p>
            </article>
        {% empty %}
            暂时没有文章了
        {% endfor %}

        <nav class="pagination">
            <ul>

                <li class="prev-page"></li>
                {% for page in all_article.pages %}
                    {% if page %}
                            {% ifequal page all_article.number %}
                            <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>

                        {% else %}
                        <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% endifequal %}
                        {% else %}
                         <li><a href="" class="none">...</a></li>
                    {% endif %}
{#                    <li class="active"><span></span></li>#}

                {% endfor %}
                {% if all_article.has_next %}
                    <li class="next-page"><a href="?{{ all_article.next_page_number.querystring }}">下一页</a></li>
                {% endif %}


            </ul>
        </nav>

    </div>
{% endblock %}